import requests
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import json

#personal data array collects all the dates of interest for the project
personal_data = {
    'Interest dates': [],
}

#allows user to add as amany dates as they want
while True:
    interest_dates = input("Enter interest dates in YYYY-MM-DD format or nothing to continue: ")
    if interest_dates == "":
        break
    personal_data['Interest dates'].append(interest_dates)

#makes a data frame out of the dates and writes them to a csv file
# CHECKLIST ITEM #8.2
dates_df = pd.DataFrame(personal_data)
dates_df.to_csv('interest_dates.csv', index=False)

#reads csv file and prints it out
dates = pd.read_csv("interest_dates.csv")
print(dates)

#api keys generated by nasas public apis
# CHECKLIST ITEM #10.4 and 10.5
api_key = "8rwe6cRZTAU2PJQdI3UnHJFhINTMT6yV7fN1VgfF"
base_url = "https://api.nasa.gov/neo/rest/v1/feed"

#a for loop that loops through all the dates in the Interest dates array
for interest_date in dates['Interest dates']:
    print("DATE OF INTEREST:" + interest_date)
    print("")
    #gets the api response about specififc date
    response = requests.get(base_url, params={"start_date": interest_date, "end_date": interest_date, "api_key": api_key})
    content = response.content
    #ensures content in in json format
    asteroid_data = json.loads(content)

    if response.status_code == 200:
        #extracts the specific data about the asteroids from the json object
        asteroids = asteroid_data.get("near_earth_objects", {}).get(interest_date, [])
        asteroid_list = []

        #sets up table information by collecting certain information about every asteroid in the sky on the specified date
        for i in range(len(asteroids)):
            asteroid_info = asteroids[i]
            table_info = {
                "Name": asteroid_info["name"],
                "Max Estimated Diameter": asteroid_info["estimated_diameter"]["kilometers"]["estimated_diameter_max"],
                "Relative Velocity": asteroid_info["close_approach_data"][0]["relative_velocity"]["kilometers_per_second"],
                "Is Potentially Hazardous": asteroid_info["is_potentially_hazardous_asteroid"]
            }
            #append this information to the list
            asteroid_list.append(table_info)
        #create dataframe
        df = pd.DataFrame(asteroid_list)
        print(df)
        print("")
    else:
        print(f"Error: {response.status_code}")
        print(response.text)
    #CHECKLIST ITEM #8.4
    #write asteroid information to csv
    csv_file_path = 'asteroid_infomation.csv'
    df.to_csv(csv_file_path, index=False)


    #CHECKLIST ITEM #8.1
    #use numpy arrays to make a graph using matplotlib
    relative_velocity = np.array(df["Relative Velocity"])
    max_diameter = np.array(df["Max Estimated Diameter"])

    plt.scatter(relative_velocity, max_diameter)
    plt.title("Asteroids Scatter Plot")
    plt.xlabel("Relative Velocity (km/s)")
    plt.ylabel("Estimated Diameter (Max) in km")
    plt.show()

    #CHECKLIST ITEM #8.3
    #I used some chat gpt on the filtering part to get a sense of hpw it works
    while True:
        #prompt user to enter minimum size of asteroid they want
        diameter_filter_input = input("Enter minimum max diameter you are searching for: ")
        if(diameter_filter_input[0].isdigit):
            #turn to float
            diameter_filter = float(diameter_filter_input)
            #filter in
            condition = df['Max Estimated Diameter'] > diameter_filter
            filtered_df = df[condition]
            print("")
            print("")
            print(filtered_df)
            relative_velocity = np.array(filtered_df["Relative Velocity"])
            max_diameter = np.array(filtered_df["Max Estimated Diameter"])

            plt.scatter(relative_velocity, max_diameter)
            plt.title("Filtered Asteroids Scatter Plot")
            plt.xlabel("Relative Velocity (km/s)")
            plt.ylabel("Estimated Diameter (Max) in km")
            plt.show()
            break

